### ISSUE TITLE
Lack of almost all basic applications on Redmi 9A (dandelion) + broken pkcon

### ISSUE THREAD

**Issue by ManWithTheHat** [ubports/ubuntu-touch#2105]
- Device: Redmi 9A (dandelion)
- Channel: Devel
- Build: 2023-02-11

### Steps to reproduce
Just install the system via UBPorts Installer on Xiaomi Redmi 9A (I also heard that the same picture is observed on FP4)

### Expected behavior
Standard applications must be present and work properly + if necessary (for example, as in this case when it is necessary to install open store) pkcon must work properly and allow .click applications to be installed from the console

### Actual behavior
There are no applications at all ... There are only those that are installed in the /usr/share directory ... But there are no click applications ... Even OpenStore is missing + when trying to install a .click application using the "pkcon --allow-untrusted install-local package.click" command, we get a critical error (access to the terminal is via adb shell )

### Illustrations (missing apps)
A photo of the situation so that it would be clear what I mean: 
![photo_2023-02-11_19-27-53](https://user-images.githubusercontent.com/125133533/218260759-1cf1d9d0-33d7-4db7-9c7f-da3c4946f1ce.jpg)

### Logfiles and additional information
Error from pkcon when trying to install OpenStore and other .click apps -

phablet@ubuntu-phablet:~$ pkcon --allow-untrusted install-local openstore.openstore-team_3.3.7_armhf.click
Installing files              [=========================]
Finished                      [=========================]
Installing files              [=========================]
Waiting for authentication    [=========================]
Starting                      [=========================]
Finished                      [=========================]
 Fatal error: /home/phablet/Downloads/openstore.openstore-team_3.3.7_armhf.click failed to install.
WARNING:root:Signature check failed, but installing anyway as requested
Traceback (most recent call last):
  File "/usr/bin/aa-clickhook", line 197, in <module>
    sys.exit(main())
  File "/usr/bin/aa-clickhook", line 142, in main
    apparmor_profiles)
  File "/usr/lib/python3/dist-packages/apparmor/click.py", line 745, in get_missing_profiles
    name = AppName(click_name=hook)
  File "/usr/lib/python3/dist-packages/apparmor/click.py", line 424, in __init__
    self.click_name = click_name
  File "/usr/lib/python3/dist-packages/apparmor/click.py", line 440, in click_name
    (click_name))
apparmor.common.AppArmorException: "invalid click manifest name '*'"
Traceback (most recent call last):
  File "/usr/bin/click", line 110, in <module>
    sys.exit(main())
  File "/usr/bin/click", line 106, in main
    return mod.run(args)
  File "/usr/lib/python3/dist-packages/click_package/commands/install.py", line 66, in run
    quiet=not options.verbose)
  File "/usr/lib/python3/dist-packages/click_package/install.py", line 463, in install
    path, user=user, all_users=all_users, quiet=quiet)
  File "/usr/lib/python3/dist-packages/click_package/install.py", line 447, in _unpack
    user_name=None)
GLib.Error: click_hooks_error-quark: Hook command '/usr/bin/aa-clickhook' failed: Child process exited with code 1 (6)

**Comment by ManWithTheHat** [comment]
Addition: This is if everything is on version 16.04 (xenial) ... I decided to add so that there would be no thoughts that this is a problem in 20.04

**Comment by Totemsky** [comment]
After today's update, the missing apps were introduced.
OpenStore is functional but did not install. It was necessary to put the tape phone in the default settings, then the installation was successful.
![screenshot20230223_220606516](https://user-images.githubusercontent.com/126206790/221042855-4e7b1da9-93f2-4af1-bb54-e48d89ad8700.png)

**Comment by fdciabdul** [comment]
how do you install this on redmi 9a? 

cuz there's no redmi 9a on ubport device list

**Comment by Totemsky** [comment]
redmi 9a (dandelion) was in the list about a year back, the programmer who prepared it ended the project

Odesláno z aplikace Pošta pro Windows

Od: taqin
Odesláno:úterý 14. listopadu 2023 21:59
Komu: ubports/ubuntu-touch
Kopie: Totemsky; Comment
Předmět: Re: [ubports/ubuntu-touch] Lack of almost all basic applications onRedmi 9A (dandelion) + broken pkcon (Issue #2105)

how do you install this on redmi 9a?
cuz there's no redmi 9a on ubport device list
