### ISSUE TITLE
Update failed - FileNotFoundError: [Errno2] No such file or directory: '/android/cahce/recovery'

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#314]
- Device:fp2
- Channel:devel
- Build:163

can't update althoug updates are available. i get this message "Update failed - FileNotFoundError: [Errno2] No such file or directory: '/android/cahce/recovery'"

![cuu](https://user-images.githubusercontent.com/333589/31909231-12f8c014-b842-11e7-92f4-5fa15d56b52d.jpg)

backtracking a bit, not sure if this is a coincidence or a consequence but i tried to flash 16.04 devel before and i got into this bug https://github.com/ubports/ubuntu-touch/issues/313 with the " Can't boot recovery image"

i ended up in this state due to a chain of bugs :D , it all started with using the stable channel and just changing the channel to Release Candidate. (nothing unusual) but run into this bug https://github.com/ubports/ubuntu-touch/issues/294 . and then i updated to devel/15,04 as a workaround.

now i'm not sure what to do next since it looks like i will not be able to flash with ubuntu-installer https://github.com/ubports/ubports-installer/issues/40

maybe try magic device tool and flash stable?

**Comment by NeoTheThird** [comment]
While we're working on ubports/ubports-installer#39, you can still use older versions of the installer that are not affected by this: https://github.com/ubports/ubports-installer/releases/tag/0.1.5-beta

**Comment by UniversalSuperBox** [comment]
Closing due to inactivity without confirmation

**Comment by wdehoog** [comment]
Even though it is closed I'd like to add my log 
```
phablet@ubuntu-phablet:~$ sudo system-image-cli -b 0 --progress=dots --verbose
[systemimage] Dec 05 14:05:44 2020 (8604) running state machine [ubports-touch/16.04/devel/bacon]
[systemimage] Dec 05 14:05:44 2020 (8604) Looking for blacklist: https://system-image.ubports.com/gpg/blacklist.tar.xz
[systemimage] Dec 05 14:05:44 2020 (8604) [0xb61624b0] Requesting group download:
        https://system-image.ubports.com/gpg/blacklist.tar.xz -> /var/lib/system-image/keyring.tar.xz
        https://system-image.ubports.com/gpg/blacklist.tar.xz.asc -> /var/lib/system-image/keyring.tar.xz.asc

[systemimage] Dec 05 14:05:44 2020 (8604) Allow GSM? No
[systemimage] Dec 05 14:05:44 2020 (8604) [/com/canonical/applications/download/7c01ffb2111f46dab27d88490f5c1555] Running group download reactor
[systemimage] Dec 05 14:05:44 2020 (8604) self: <UDMDownloadManager at 0xb61624b0>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb61541b0> :1.135 /com/canonical/applications/download/7c01ffb2111f46dab27d88490f5c1555 at 0xb6162510> implementing 'com.canonical.applications.GroupDownload' at 0xb61623b0>
[systemimage] Dec 05 14:05:44 2020 (8604) [/com/canonical/applications/download/7c01ffb2111f46dab27d88490f5c1555] Group download reactor done
[systemimage] Dec 05 14:05:46 2020 (8604) Local blacklist file: /var/lib/system-image/blacklist.tar.xz
[systemimage] Dec 05 14:05:46 2020 (8604) Looking for: https://system-image.ubports.com/channels.json
[systemimage] Dec 05 14:05:46 2020 (8604) [0xb61620f0] Requesting group download:
        https://system-image.ubports.com/channels.json -> /tmp/system-image-u_0s4219/channels.json
        https://system-image.ubports.com/channels.json.asc -> /tmp/system-image-u_0s4219/channels.json.asc

[systemimage] Dec 05 14:05:46 2020 (8604) Allow GSM? No
[systemimage] Dec 05 14:05:46 2020 (8604) [/com/canonical/applications/download/3093336544e64672893337b3895663a7] Running group download reactor
[systemimage] Dec 05 14:05:46 2020 (8604) self: <UDMDownloadManager at 0xb61620f0>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb61541b0> :1.135 /com/canonical/applications/download/3093336544e64672893337b3895663a7 at 0xb61a57b0> implementing 'com.canonical.applications.GroupDownload' at 0xb6162690>
.
.
[systemimage] Dec 05 14:05:46 2020 (8604) [/com/canonical/applications/download/3093336544e64672893337b3895663a7] Group download reactor done
[systemimage] Dec 05 14:05:50 2020 (8604) Local channels file: /tmp/system-image-u_0s4219/channels.json
[systemimage] Dec 05 14:05:50 2020 (8604) got channel: ubports-touch/16.04/devel
[systemimage] Dec 05 14:05:50 2020 (8604) found channel/device entry: ubports-touch/16.04/devel/bacon
[systemimage] Dec 05 14:05:50 2020 (8604) [0xb61620f0] Requesting group download:
        https://system-image.ubports.com/ubports-touch/16.04/devel/bacon/index.json -> /tmp/system-image-u_0s4219/index.json
        https://system-image.ubports.com/ubports-touch/16.04/devel/bacon/index.json.asc -> /tmp/system-image-u_0s4219/index.json.asc

[systemimage] Dec 05 14:05:50 2020 (8604) Allow GSM? No
[systemimage] Dec 05 14:05:50 2020 (8604) [/com/canonical/applications/download/6b1549a9cb874a18bbc465365cc525a7] Running group download reactor
[systemimage] Dec 05 14:05:50 2020 (8604) self: <UDMDownloadManager at 0xb61620f0>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb61541b0> :1.135 /com/canonical/applications/download/6b1549a9cb874a18bbc465365cc525a7 at 0xb61a57b0> implementing 'com.canonical.applications.GroupDownload' at 0xb61627d0>
.
.
[systemimage] Dec 05 14:05:50 2020 (8604) [/com/canonical/applications/download/6b1549a9cb874a18bbc465365cc525a7] Group download reactor done
[systemimage] Dec 05 14:05:54 2020 (8604) Upgrade path is 1726
[systemimage] Dec 05 14:05:54 2020 (8604) uncaught exception in state machine
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 133, in __next__
    step()
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 507, in _download_files
    for filename in os.listdir(cache_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/android/cache/recovery'
Exception occurred during update; see log file for details
[systemimage] Dec 05 14:05:54 2020 (8604) system-image-cli exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/systemimage/main.py", line 402, in main
    list(state)
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 133, in __next__
    step()
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 507, in _download_files
    for filename in os.listdir(cache_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/android/cache/recovery'
[systemimage] Dec 05 14:05:54 2020 (8604) state machine finished

```
